version: 0.10.2

theme: bootstrap_tweeter
locale: pl

themes: [bootstrap_tweeter]
locales: [en, pl]
msgs_per_page_table: [15, 20, 25, 30, 35, 40, 45, 50]
msg_send_type: [html, text]
msg_image_view_as: [attachment, thumbnail]
msg_image_thumbnail_size: [128x128, 128x96, 192x192, 192x144, 256x256, 256x192]

contacts_table_fields: [name, email, info]
contacts_per_page: 25

links_table_fields: [url, info]
links_per_page: 30

# display order of system folders (array shows position index of folder)
#                      SYS_TRASH = 1
#                        SYS_INBOX = 2
#                          SYS_SENT = 3 
#                            SYS_DRAFTS = 4
system_folders_order: [3, 0, 1, 2]

notes_table_fields: [title]
notes_per_page: 10

servers_table_fields: [name, port, use_ssl, use_tls, for_imap, for_smtp, auth]

msgs_per_page: 20
msgs_refresh_time: 300
msgs_send_type: html
msgs_update_time: 600
msgs_inbox_view_fields: [from_addr, subject, date, size]
msgs_sent_view_fields: [to_addr, subject, date, size]

msg_subject_length: 50
msg_address_length: 35
msg_search_fields: [subject, from, to]
msg_upload_dir: "tmp/uploads"

contact_tmp_filename: contact_import
link_tmp_filename: link_import

# if encoding can not be get from data
msg_unknown_charset: ISO-8859-2

imap_debug: true
imap_use_ssl: 'false'
imap_port: 143
imap_ssl_port: 993
imap_bye_timeout_retry_seconds: 2
imap_fetch_slice: 20

smtp_port: 25

session_encryption: true
session_password: asDD3s2@sAdc983#

mailbox_max_parent_folder_depth: 3

# array of logins which only can login to application, comment it to allow everyone to login
only_can_logins: ['john']
